export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readMinutes: number;
  /** Feature image path (public/). */
  image: string;
  /** Full article body as simple markdown-ish paragraphs (rendered simply). */
  body: string[];
}

export const POSTS: BlogPost[] = [
  {
    slug: "how-to-calculate-fertilizer-dose-per-acre",
    image: "/blog/fertilizer-calculation.webp",
    title: "How to Calculate Fertilizer Dose Per Acre (With a Worked Example)",
    excerpt:
      "The exact formula agronomists use to convert a nutrient recommendation into bags of urea, DAP and MOP — explained with a real wheat example.",
    category: "Guides",
    date: "2026-09-12",
    readMinutes: 7,
    body: [
      "Every fertilizer recommendation starts as nutrients, not products. An agronomist will tell you wheat needs 50 kg nitrogen, 25 kg phosphorus (P₂O₅) and 20 kg potash (K₂O) per acre — but you buy urea, DAP and MOP. The bridge between the two is one formula:",
      "Fertilizer required (kg) = (nutrient required × 100) ÷ nutrient percentage in the fertilizer.",
      "This works because the percentage on the bag tells you how many kilograms of nutrient are in every 100 kg of product. Urea is 46% nitrogen, DAP is 18% nitrogen and 46% phosphate, MOP is 60% potash.",
      "Worked example — wheat per acre needing 50–25–20:",
      "Step 1 — Phosphorus first. DAP is 46% P₂O₅: (25 × 100) ÷ 46 = 54.3 kg DAP per acre. That DAP also carries nitrogen: 54.3 × 18% = 9.8 kg N.",
      "Step 2 — Remaining nitrogen from urea. Needed 50 kg, already have 9.8 kg, so 40.2 kg remain: (40.2 × 100) ÷ 46 = 87.4 kg urea per acre.",
      "Step 3 — Potassium from MOP: (20 × 100) ÷ 60 = 33.3 kg MOP per acre.",
      "Final answer: about 54 kg DAP + 87 kg urea + 33 kg MOP per acre. Our calculator above does this instantly for any area in acres, kanal, marla or hectares — and shows every step, so you can verify the math yourself.",
      "One caution: recommendations vary by soil test and region. Use the calculated dose as your starting point and confirm with your local agriculture officer.",
    ],
  },
  {
    slug: "urea-vs-dap-what-each-does",
    image: "/blog/urea-vs-dap.webp",
    title: "Urea vs DAP: What Each Fertilizer Actually Does",
    excerpt:
      "Both supply nitrogen, but they are not interchangeable. Here's what each one does in the soil and when to use which.",
    category: "Fertilizers",
    date: "2026-08-28",
    readMinutes: 5,
    body: [
      "Urea (46% nitrogen) and DAP (18% nitrogen, 46% phosphate) are the two most-used fertilizers in Pakistan and India — and the most confused.",
      "Urea is a nitrogen specialist. Its 46% N is the highest concentration of any common solid fertilizer, which is why it is the go-to for top-dressing: quick nitrogen when the crop is growing fast. Split it into two or three applications; a single heavy dose risks losses to the air (volatilization) and causes lodging.",
      "DAP is primarily a phosphorus fertilizer that happens to carry nitrogen. Phosphorus barely moves in soil, so DAP must go down at sowing, near the seed zone — top-dressed phosphorus is largely wasted. Its 18% nitrogen is a bonus that counts toward the total nitrogen bill.",
      "The practical rule: DAP at sowing for phosphorus (plus its nitrogen), urea in splits for the remaining nitrogen. Never try to meet a phosphorus need with urea, and never pay DAP prices just for nitrogen.",
      "Check the NPK table in our fertilizer library before buying — the percentages on the bag are the only numbers that matter for the calculation.",
    ],
  },
  {
    slug: "why-soil-testing-saves-money",
    image: "/blog/soil-testing.webp",
    title: "Why Soil Testing Saves You Money Every Season",
    excerpt:
      "A soil test costs less than a single bag of DAP — and stops you buying fertilizer your field doesn't need.",
    category: "Soil Health",
    date: "2026-08-10",
    readMinutes: 6,
    body: [
      "Most farmers fertilize by habit: the same bags, every season, regardless of what the soil already holds. A soil test breaks that habit with facts.",
      "A basic soil health test reports available nitrogen, phosphorus, potassium, pH, organic matter and often zinc. With those numbers, the standard fertilizer recommendation can be adjusted up or down — many fields test high in phosphorus after years of DAP use, meaning the DAP dose can be cut without any yield penalty.",
      "The economics are simple: one test typically costs less than a single 50 kg bag of DAP, while skipping even half a bag per acre across your holding pays for the test many times over.",
      "How often? Test once every two to three years, or whenever you take over new land. Sample from 6–8 spots per field at 0–15 cm depth, mix, and send about half a kilogram to your district soil laboratory.",
      "Use our calculator with the adjusted nutrient figures from your soil health card, and keep the card — comparing tests over years shows whether your soil is improving or degrading.",
    ],
  },
  {
    "body": [
      "If you want to know how to read a fertilizer bag label, start with the three big numbers printed on the front, like 18-46-0 or 46-0-0. Those three numbers always stand for nitrogen (N), phosphorus (P), and potassium (K) in that exact order, and they tell you what percentage of the bag's weight is each nutrient. So a bag of urea labeled 46-0-0 contains 46 percent nitrogen, no phosphorus, and no potassium.",
      "That percentage is by weight, and this is the single most useful fact on the whole bag. A 50 kilogram bag of urea at 46 percent nitrogen holds 23 kilograms of actual nitrogen, because 50 multiplied by 0.46 equals 23. The rest of the bag is carrier material and coating that helps the granules store well and spread evenly. Once you understand this one idea, you can convert any bag into real nutrient numbers in your head.",
      "The order N-P-K never changes, no matter which company makes the bag. The first number is always nitrogen, shown as total N. The second is phosphorus, but note that it is expressed as phosphate, written P2O5, not elemental phosphorus. The third is potassium, expressed as potash, written K2O. This convention is the same worldwide, which is why a bag in Pakistan, India, or Brazil reads the same way.",
      "A zero on the label is just as informative as a big number. When you see 18-46-0 on DAP, the zero tells you there is no potassium in it at all. When you see 0-0-60 on MOP, the two zeros tell you it supplies only potassium. Straight fertilizers like these carry one or two nutrients, while compound fertilizers like 19-19-19 carry all three in equal shares. Neither type is better in general; they simply solve different problems.",
      "Beyond the three big numbers, the label usually lists the nutrient in chemical form. Urea bags say the nitrogen is in amide form, DAP says ammoniacal nitrogen plus water-soluble phosphate, and MOP says the potassium comes as potassium chloride. This matters because it tells you how fast the nutrient becomes available and whether there are side effects, like the chloride in MOP, which some chloride-sensitive crops dislike in large amounts.",
      "The label also carries the net weight, almost always 50 kilograms for granular fertilizers in South Asia. Do not confuse bag weight with nutrient weight. A recommendation that says apply 120 kilograms of nitrogen per hectare does not mean four bags of urea. Because urea is 46 percent nitrogen, you divide 120 by 0.46, which gives about 261 kilograms of urea, or just over five 50 kilogram bags per hectare.",
      "That division is the core dose formula and it works for every fertilizer: fertilizer in kilograms equals the nutrient needed multiplied by 100, divided by the nutrient percentage on the label. Say your soil test calls for 60 kilograms of phosphate per hectare and you are using DAP at 18-46-0. Multiply 60 by 100 to get 6000, divide by 46, and you get about 130 kilograms of DAP per hectare, which is roughly two and a half bags. As a bonus, that DAP also gives you nitrogen, since 130 kilograms times 18 percent equals about 23 kilograms of nitrogen, so you subtract that from your planned urea dose later.",
      "Our /calculator page runs exactly this math for you, but reading the label yourself is still worth it, because it is how you check that the shopkeeper handed you the right bag. Fake or mislabeled fertilizer is a real problem in many markets, and a bag whose print is blurry, whose grade does not match any standard product, or whose weight feels off deserves a second look before you pay.",
      "The fine print on the bag usually includes storage and handling guidance, and it is worth reading once. Most granular fertilizers absorb moisture from the air, which is why bags say to store in a cool dry place and to reseal opened bags. Lumpy, damp urea still contains nitrogen, but it spreads unevenly through a broadcast spreader, so some rows get too much and some get too little.",
      "Another useful line on many labels is the application guidance or the crop it is registered for. This is general advice, not a prescription for your field. Your actual dose should come from a soil test or a published recommendation for your crop and region, which is what our /fertilizers pages list for each product, including typical nutrient content and common uses.",
      "A common mistake is assuming bigger numbers mean a stronger or better fertilizer. A 19-19-19 bag is not stronger than urea; it is simply balanced. If your soil already has plenty of potassium, paying for the potassium in a balanced grade is wasted money. The cheapest bag is the one whose nutrients match what your soil test says you actually lack.",
      "Another frequent error is adding up the three numbers and thinking the total should be 100. It never will be, because the numbers are percentages of three different nutrient forms measured on different scales, and the rest is carrier. A 10-26-26 bag contains 62 percent named nutrients and 38 percent other material, and that is completely normal.",
      "Farmers sometimes also misread liquid fertilizer labels, where the numbers may be given by volume rather than weight, with a density figure printed nearby. If the bag or bottle gives density, multiply the percentage by the density to get nutrient per litre. The N-P-K order rule stays the same, so your reading skill transfers directly.",
      "So the two-minute routine is this: read the three numbers left to right as N, P, K; multiply each by the bag weight to get actual nutrient kilograms; and use the dose formula to turn a nutrient recommendation into bags per acre or per hectare. Do that, and the label stops being decoration and becomes a tool.",
      "To put it into practice, open our /calculator, pick your crop, and enter your land area. The calculator shows the full working, from nutrient need to bags of each fertilizer, using the same formula you just learned. Pair it with the product details on /fertilizers and the common questions on /faq, and you will buy and apply fertilizer with complete confidence."
    ],
    "category": "Fertilizers",
    "date": "2026-10-06",
    "excerpt": "Learn how to read a fertilizer bag label: the three NPK numbers tell you exactly how much nitrogen, phosphorus, and potassium each bag holds.",
    "image": "/blog/how-to-read-fertilizer-bag-label.webp",
    "readMinutes": 9,
    "slug": "how-to-read-fertilizer-bag-label",
    "title": "How to Read a Fertilizer Bag Label: NPK Numbers Explained"
  },
  {
    "body": [
      "The organic vs chemical fertilizer debate usually gets framed as a fight, with one side cast as the villain. That framing helps nobody. Chemical fertilizers like urea and DAP supply nutrients in exact, fast-acting forms, while organic sources like farmyard manure and compost supply nutrients slowly along with organic matter. Both have genuine strengths and genuine drawbacks, and most experienced farmers end up using a mix rather than picking a team.",
      "Start with what chemical fertilizers do well. Their biggest advantage is precision. A bag of urea is 46-0-0, every time, so you know exactly how many kilograms of nitrogen you are applying. That precision lets you match a soil-test recommendation almost exactly, which is why our /calculator can turn a nutrient target into an exact bag count. You cannot do that with a tractor-load of manure whose nutrient content varies from load to load.",
      "Speed is the second advantage. Chemical fertilizers dissolve in soil moisture and become plant-available within days. When a wheat crop shows nitrogen deficiency at tillering, a top-dressing of urea corrects it quickly. Organic sources release nutrients over weeks and months as microbes break them down, which is too slow for an in-season rescue.",
      "The third advantage is logistics. Chemical fertilizers are concentrated, so a few bags cover an acre. Organic manures are bulky and dilute. Farmyard manure typically contains well under one percent nitrogen, so supplying the same nitrogen as one bag of urea can take several tonnes of manure, plus the labor to transport and spread it. For a farmer without nearby livestock, that math rarely works.",
      "Now the honest downsides of chemical fertilizers. The biggest is that they feed the plant but not the soil. Years of applying only urea and DAP, with all crop residue removed or burned, gradually depletes soil organic matter. Organic matter is what holds soil structure together, retains moisture, and supports the microbial life that cycles nutrients naturally. A soil treated only with chemicals for decades often becomes harder, less absorbent, and more dependent on ever-larger fertilizer doses.",
      "The second downside is the margin for error. Because chemical fertilizers are concentrated salts, over-application causes fertilizer burn, nutrient imbalances, and wasted money much faster than organic sources do. Applying double the needed DAP does not double your yield; the excess phosphorus mostly locks up in the soil, and the extra nitrogen can leach away or damage seedlings.",
      "The third downside is price exposure. Chemical fertilizer prices swing with energy and global markets, and when prices spike, farmers who depend entirely on bagged fertilizer feel it immediately. Organic sources produced on the farm, like manure and compost, are insulated from those swings, though they carry their own labor cost.",
      "Turn now to organic fertilizers, and give them the same honest treatment. Their standout strength is soil building. Manure, compost, and green manures add organic matter, improve soil structure, increase water retention, and feed beneficial microbes. A soil rich in organic matter holds onto chemical fertilizer nutrients better too, so organics make your bagged fertilizer work more efficiently.",
      "Their second strength is the slow, steady release of nutrients, including secondary nutrients and micronutrients that straight chemical fertilizers often lack. Manure supplies small amounts of zinc, iron, and boron alongside the big three nutrients. These extras rarely make the label, but over years they help prevent the hidden micronutrient deficiencies that quietly cap yields.",
      "The third strength is cost and availability for livestock-owning households. If you already keep cattle, manure is essentially free apart from labor. Composting crop residue costs nothing but time and turns a waste problem into a resource.",
      "The drawbacks of organics are equally real. First, the nutrient content is low and unpredictable. One batch of farmyard manure might have noticeably more nitrogen than the next, depending on the animals, feed, bedding, and how long it sat in the heap. You cannot plan a precise dose from it, which is why agronomists treat manure as a soil conditioner first and a nutrient source second.",
      "Second, the release is slow. Fresh manure applied just before sowing will not feed the young crop in its first critical weeks. Poorly decomposed manure can even temporarily tie up soil nitrogen as microbes consume it to break down the carbon-rich material, a process that can starve seedlings of nitrogen for a short period. Well-rotted, composted manure avoids this problem, which is why composting matters.",
      "Third, bulk and handling. Moving tonnes of manure per acre takes real labor and transport, and raw manure can carry weed seeds and pathogens if it has not been properly composted. Hot composting, where the heap genuinely heats up, kills most weed seeds and pathogens, but a cold, neglected heap does not.",
      "So how should a farmer actually decide? The practical answer used by most agronomists is integrated nutrient management: use soil-test-based chemical fertilizer for precision and timing, and add organic matter every year for soil health. For example, apply well-rotted manure or compost before sowing to build the soil, then use the /calculator to work out the exact urea, DAP, and MOP dose your crop still needs on top of it.",
      "A few practical rules make the combination work. Compost manure before applying so nutrients release predictably and weed seeds die. Do not count manure as a full replacement for phosphorus and potassium unless you have lab analysis of that specific batch. Keep applying chemical fertilizer by the soil test, not by habit, and watch the field: darker, crumblier soil and better moisture retention over a few seasons are the signs your organic additions are paying off.",
      "The common mistakes on both sides are mirror images. Chemical-only farmers often skip soil testing and apply the same bags every year out of habit, slowly acidifying or salting their soil. Organic-only enthusiasts sometimes assume manure alone can meet a high-yielding crop's full nutrient demand, then wonder why yields plateau. Both mistakes come from treating one approach as a belief rather than a tool.",
      "In short, chemical fertilizers are precise, fast, and concentrated but do nothing for soil structure and punish over-application. Organic fertilizers build soil and supply a broad spectrum of nutrients but are dilute, variable, and slow. Use chemicals for what the crop needs this season, use organics for what the soil needs every season, and let a soil test referee between them. Our /faq answers the practical questions that come up along the way, and the /planting-calendar helps you time every application to the crop's actual growth stages."
    ],
    "category": "Fertilizers",
    "date": "2026-10-06",
    "excerpt": "Organic vs chemical fertilizer, honestly compared: chemicals feed the crop fast and precisely, organics build the soil slowly. Most farms need both.",
    "image": "/blog/organic-vs-chemical-fertilizer-pros-cons.webp",
    "readMinutes": 10,
    "slug": "organic-vs-chemical-fertilizer-pros-cons",
    "title": "Organic vs Chemical Fertilizer: Honest Pros and Cons"
  },
  {
    "body": [
      "Fertilizer burn symptoms are easy to misread, and that misreading costs farmers twice: first the damaged crop, then the wrong treatment. Burnt plants look thirsty, with brown crispy leaf margins, wilting even in moist soil, and young seedlings that emerge and then collapse. The direct answer is that fertilizer burn is salt injury, not a disease and not drought, and it happens when too much fertilizer salt sits near roots or on leaves, pulling water out of plant tissue instead of into it.",
      "To understand why, remember that all chemical fertilizers are salts. Urea, DAP, and MOP dissolve into ions in soil water, and roots absorb water by osmosis, which only works when the soil solution is less salty than the inside of the root cells. Dump a heavy dose of fertilizer near the roots and you flip that gradient: water moves out of the roots into the salty soil, and the plant dehydrates while standing in damp earth. That is why burn looks so much like drought.",
      "The classic early symptom is leaf margin burn, sometimes called tip burn. The edges and tips of leaves turn yellow, then brown and papery, while the center of the leaf may still look green. This pattern appears because salts accumulate at the leaf margins as water evaporates. In lawns and close-planted crops you may instead see irregular brown patches where the spreader overlapped and doubled the dose.",
      "Seedlings show it differently and more severely. Seeds germinating in soil with banded fertilizer too close by may fail to emerge at all, or emerge with burnt root tips and then stall. DAP placed in direct contact with seed is a well-known cause, because the seedling's tiny root system cannot escape the salty zone. This is why placement guidelines always keep fertilizer a few centimeters away from the seed row.",
      "Foliar burn is the third pattern. Spraying fertilizer solutions on leaves in hot midday sun, or at too high a concentration, leaves scorched spots where droplets sat. Urea sprays are the usual culprit. The rule is simple: foliar feeds go on in the cool of early morning or evening, at the labeled dilution, never stronger.",
      "Several common mistakes cause burn. The most frequent is simple over-application, applying more bags than the recommendation calls for, often because a previous dose seemed to work well so the farmer doubled it. The second is poor spreading: overlapping passes with a broadcast spreader, or dumping fertilizer in heaps around the base of plants instead of spreading it evenly. The third is bad timing, top-dressing urea onto dry soil with no rain or irrigation to dissolve it, so granules sit against stems and roots in concentrated form.",
      "A fourth cause surprises many people: fertilizing already stressed plants. A crop wilting from heat or drought is far more vulnerable to salt injury than a healthy one, because its roots are already struggling to take up water. Adding fertilizer to a stressed field is like adding salt to a wound, and the standard advice is to relieve the stress first, fertilize second.",
      "If you spot burn early, the fix is water, applied generously. Heavy irrigation leaches the excess salts down below the root zone, restoring the osmotic gradient so roots can drink again. Water deeply rather than in light sprinkles, because light watering just redistributes salts within the root zone. On a small vegetable plot, this can mean soaking the beds thoroughly for a couple of evenings in a row.",
      "What not to do matters as much. Do not apply more fertilizer to fix it, even if the crop looks hungry, because the nutrients are already there in excess. Do not foliar-spray anything on burnt leaves until new healthy growth appears. And do not assume the crop is dead too quickly: cereals and many vegetables can push new leaves from the growing point if the damage is only on older foliage, so give the field a week after leaching before judging the loss.",
      "For seedlings killed outright in the row, replanting may be necessary, but replant into the same salty band and you will burn the second sowing too. Either leach the band with water first or shift the new seed line slightly away from the old fertilizer band. Prevention is cheaper than either option.",
      "Preventing burn comes down to four habits. First, dose by calculation, not by guess: use the /calculator to convert your soil-test recommendation into exact bags per acre, so you never accidentally double up. Second, spread evenly and never heap fertilizer against stems. Third, keep fertilizer away from seed at sowing, banded to the side and below, not mixed in the furrow. Fourth, time top-dressings before rain or irrigation so granules dissolve and move into the soil instead of sitting concentrated on the surface.",
      "Split application is one of the best structural preventions, especially for nitrogen. Instead of putting all the urea on at sowing, apply part at sowing and the rest as top-dressings at tillering and flowering. Smaller individual doses mean lower salt concentration at any one time, and the crop actually uses nitrogen more efficiently this way, so you get better yields from the same total amount.",
      "One more honest note: organic manures can burn too. Fresh poultry manure is notoriously hot, meaning high in soluble salts and ammonia, and applying it fresh around young plants scorches them just like chemical fertilizer does. Composting manure first, or applying it well before planting, removes this risk, which is another reason composting is worth the effort.",
      "If burn has already happened, walk the field, confirm the pattern matches salt injury rather than disease or pests, leach with deep watering, hold off on further fertilizer, and let the crop recover before reassessing. Then fix the cause, not just the symptom: recalculate your dose on /calculator, check your spreader pattern, and plan split applications on the /planting-calendar so the next season's fertilizer feeds the crop instead of fighting it."
    ],
    "category": "Crop Nutrition",
    "date": "2026-10-06",
    "excerpt": "Fertilizer burn symptoms look like drought: brown leaf edges, wilting, stunted seedlings. It is salt injury, and quick watering can save the crop.",
    "image": "/blog/fertilizer-burn-symptoms-and-fix.webp",
    "readMinutes": 9,
    "slug": "fertilizer-burn-symptoms-and-fix",
    "title": "Fertilizer Burn: Symptoms and How to Fix Over-Fertilization"
  },
  {
    "body": [
      "What happens if you apply too much DAP? The short, honest answer is that you waste money and can harm the crop, without gaining yield. DAP is 18-46-0, meaning 18 percent nitrogen and 46 percent phosphate, so an overdose hits the field with excess phosphorus and excess nitrogen at the same time, and each causes its own distinct problems. More fertilizer is not more food for the plant; past the recommended dose, it becomes a pollutant in your own soil.",
      "Start with the phosphorus half, because that is the larger number on the bag. Unlike nitrogen, phosphorus barely moves in soil. When you apply more phosphate than the crop can take up, the surplus does not wash away; it reacts with calcium, iron, and aluminum in the soil and converts into insoluble compounds the plant cannot access. Agronomists call this phosphorus fixation, and it means last year's excess DAP is mostly sitting in your field as locked-up reserves, not as available nutrition.",
      "This immobility has a practical consequence: soil phosphorus levels ratchet upward year after year under repeated over-application, while the crop sees little benefit. A soil test will show high or very high phosphorus, and at that point the correct DAP dose for the next season may be small or even zero for a year. Farmers who soil-test regularly discover this and save the cost of bags they never needed; farmers who do not keep paying for phosphorus their soil already holds.",
      "Excess phosphorus also interferes with micronutrients, and zinc is the classic victim. High soil phosphorus is well known to induce or worsen zinc deficiency in crops like maize, rice, and wheat. The mechanism is a nutrient antagonism: abundant phosphate in the root zone suppresses the plant's zinc uptake, so leaves show zinc deficiency symptoms, pale striping between veins and stunted growth, even though the soil contains adequate zinc. The farmer sees a deficiency, but the cause is an excess.",
      "Iron and manganese uptake can suffer in similar ways under very high phosphorus, particularly in alkaline soils where these micronutrients are already marginally available. The pattern is always the same: the field shows a deficiency that no amount of the deficient nutrient seems to fix, because the real problem is the phosphorus excess blocking it.",
      "Now the nitrogen half of the overdose. Every 100 kilograms of DAP carries 18 kilograms of nitrogen along with its 46 kilograms of phosphate. Apply double the needed DAP and you have also doubled a chunk of your nitrogen. Excess nitrogen pushes lush, soft vegetative growth that lodges easily in cereals, delays maturity, and invites pests and fungal diseases that thrive on dense, humid canopies.",
      "In the seed furrow, excess DAP is directly dangerous to germination. DAP granules release ammonia as they dissolve, and concentrated ammonia near the seed damages the emerging root. This is the seedling burn described in our fertilizer burn guide: poor emergence, burnt root tips, and gaps in the stand. The standard safeguard is placement, banding DAP a few centimeters to the side of and below the seed, never mixed with it in the furrow.",
      "There is also the environmental side, which matters even if it does not show in this season's yield. Phosphorus that leaves the field in eroded soil ends up in ditches, ponds, and rivers, where it feeds algal blooms that deplete oxygen and harm aquatic life. Nitrogen from the DAP's ammonium fraction can convert to nitrate and leach toward groundwater. Over-application turns your field into a source of pollution you are paying to create.",
      "How much is too much? The honest answer is that it depends on your soil test, not on a fixed number. A field testing low in phosphorus genuinely needs a full DAP dose, perhaps around 130 kilograms per hectare to supply roughly 60 kilograms of phosphate, which is about two and a half 50 kilogram bags. That same dose on a field already testing high in phosphorus is too much. The bag count is only correct relative to what the soil lacks, which is why the dose always starts from a soil test.",
      "A useful cross-check is the DAP-first method our /calculator uses. Because DAP supplies both nutrients, the calculator works out the DAP dose from the phosphorus need first, then calculates how much nitrogen that DAP already provides, and only then tops up the remaining nitrogen with urea. If you run your numbers through it and your usual DAP purchase comes out much higher than the calculated dose, that gap is the excess you have been applying.",
      "If you have already over-applied, the remedies are straightforward but slow. Do not try to flush phosphorus out with irrigation the way you would flush excess nitrogen salts; phosphorus does not leach, so heavy watering just wastes water. Instead, cut or skip DAP for the next season or two based on a fresh soil test, and let the crop draw down the accumulated reserves. For the nitrogen excess, deep watering can help move nitrate below the root zone, and splitting future nitrogen into smaller top-dressings prevents a repeat.",
      "Watch for the zinc deficiency signal in the following season, especially in maize and rice. If interveinal chlorosis appears on a field with a history of heavy DAP use, consider a targeted zinc application rather than more DAP. Correcting the induced deficiency directly is cheaper and faster than waiting for the phosphorus excess to fade.",
      "The common mistakes that lead here are all preventable. Applying DAP by habit every season without soil testing is the biggest one. Broadcasting extra DAP as insurance is another; phosphorus is not insurance, it is inventory that locks up. And mixing DAP with the seed to save a field pass trades a small labor saving for a real germination risk.",
      "DAP is an excellent fertilizer when the dose matches the need: it delivers phosphate exactly where young roots can reach it and contributes useful starter nitrogen at the same time. The problems start only when the dose exceeds the need. Soil-test first, calculate the bags on /calculator, place it beside the seed rather than with it, and revisit the numbers on /faq whenever a new question comes up. Used that way, DAP builds yields; overused, it builds up problems."
    ],
    "category": "Fertilizers",
    "date": "2026-10-06",
    "excerpt": "Too much DAP wastes money and harms crops: excess phosphorus locks up in soil, can trigger zinc deficiency, and extra nitrogen risks seedling damage.",
    "image": "/blog/too-much-dap-effects.webp",
    "readMinutes": 9,
    "slug": "too-much-dap-effects",
    "title": "What Happens If You Apply Too Much DAP?"
  },
  {
    "slug": "best-time-of-day-to-apply-fertilizer",
    "title": "Best Time of Day to Apply Fertilizer (And Why It Matters)",
    "excerpt": "The best time of day to apply fertilizer is early morning or late evening, when cool temperatures and calm air keep nutrients working for your crop instead of escaping into the air.",
    "category": "Guides",
    "date": "2026-10-06",
    "readMinutes": 6,
    "image": "/blog/best-time-of-day-to-apply-fertilizer.webp",
    "body": [
      "The best time of day to apply fertilizer is early morning or late in the evening. During these cooler hours the sun is low, the air is usually calm, and the soil is often damp from dew or the previous night. Those three conditions keep more of your fertilizer working for the plant and less of it lost to the air. The worst time, by contrast, is the middle of the day, when heat, bright sun, and wind all work against you.",
      "The main reason timing matters is a process called volatilization, and it mostly affects urea, the 46-0-0 fertilizer that most farmers use for nitrogen. When urea sits on a warm, moist soil surface, it converts into ammonia gas and drifts away. This happens fastest in hot, sunny, windy weather. A bag of urea spread at noon on a hot day can lose a meaningful share of its nitrogen before it ever reaches the roots, while the same bag spread in the cool of the morning loses far less.",
      "Heat speeds up every chemical reaction on the soil surface, and the conversion of urea to ammonia is no exception. Soil that has been baking in the midday sun is the worst possible landing spot for urea granules. In the morning the soil is cooler, so the conversion happens slowly, and that slow pace gives you time to water the granules in or let them dissolve into the soil on their own.",
      "Wind is the second enemy. Even on a warm day, still air lets ammonia linger close to the soil surface, where some of it can be recaptured. A steady breeze carries it away permanently. Mornings and evenings are generally calmer than midday, which is another reason the bookends of the day are better. If you can feel a strong wind on your face, it is not a good moment to spread urea.",
      "Morning dew is actually your friend. Granules that land on dew-damp soil start dissolving right away, and dissolved urea moves down into the soil with the first watering or light rain. Once urea is a few centimetres below the surface, it is protected from volatilization. This is why many experienced farmers spread fertilizer at first light: the dew does half the incorporation work for free.",
      "The single most effective thing you can do after spreading is to water the fertilizer in. A light irrigation, or timing your application just before a gentle rain, washes the granules into the root zone where they belong. If you spread in the morning, you can irrigate the same day and finish the job. If you spread at noon and cannot water until evening, the hottest hours are lost to the air.",
      "Here is a simple routine that works in most situations. First, check the weather forecast and pick a day with light winds and no heavy rain expected. Second, start early in the morning, ideally within a couple of hours of sunrise. Third, spread evenly and at the correct dose, because timing cannot fix over-application. Fourth, irrigate lightly the same morning so the nutrients move into the soil.",
      "If morning is impossible and you must work at midday, you can still reduce losses. Incorporate the fertilizer into the soil with a light hoeing or harrowing instead of leaving it on the surface, or irrigate immediately after spreading. For liquid fertilizers the same logic applies, and it applies even more strongly, because a fine spray dries on hot leaf surfaces within minutes and can scorch them.",
      "Foliar sprays, where fertilizer is sprayed directly onto leaves, follow the same timing rule for a different reason. Sprayed in the cool of the morning or evening, the droplets stay wet long enough for the leaves to absorb the nutrients. Sprayed at midday, they dry almost instantly, absorption stops, and concentrated droplets can burn the leaf tissue. Never do foliar feeding under a harsh midday sun.",
      "Timing matters more in hot seasons and hot climates than in cool ones. In the middle of summer the difference between a morning and a midday application can be large, while on a cool, overcast autumn day the penalty for imperfect timing is much smaller. Match your care to the conditions: the hotter and windier it is, the more strictly you should stick to morning or evening.",
      "The most common mistakes are easy to list. Spreading urea at noon in summer and leaving it on the surface is the classic one. Another is fertilizing right before a heavy downpour, which washes granules away instead of watering them in. A third is applying fertilizer to drought-stressed, wilted plants at midday, which adds salt stress to water stress. And a fourth is simply using the wrong dose and hoping good timing will compensate, which it will not.",
      "Evening application deserves a word of its own. Late evening, after the heat has faded, is nearly as good as early morning. The one caution is with foliar sprays: leaves that stay wet all night in humid weather can invite fungal problems, so for sprays, morning is the safer of the two. For granular fertilizer worked into the soil, morning and evening are equally fine.",
      "Different fertilizer types have slightly different sensitivities. Urea is the most timing-sensitive because of volatilization. DAP, the 18-46-0 fertilizer, and MOP, the 0-0-60 fertilizer, are less affected by surface losses, but they still benefit from being watered in so the nutrients reach the root zone instead of sitting on top. The morning-or-evening habit is good practice for all of them.",
      "Getting the timing right is only half the job; the dose has to be right too. Use the dose calculator at /calculator to work out exactly how much urea, DAP, and MOP your crop and area need, browse fertilizer grades and what each one does at /fertilizers, and check /faq if you have questions about mixing products or application methods. Right dose, right time, right result."
    ]
  },
  {
    "slug": "does-rain-wash-away-fertilizer",
    "title": "Does Rain Wash Away Fertilizer? What Actually Happens",
    "excerpt": "Does rain wash away fertilizer? Light rain usually helps by moving nutrients into the soil, while heavy rain shortly after application can cause runoff and leaching. Here is what actually happens.",
    "category": "Guides",
    "date": "2026-10-06",
    "readMinutes": 6,
    "image": "/blog/does-rain-wash-away-fertilizer.webp",
    "body": [
      "Does rain wash away fertilizer? The honest answer is: it depends on the rain. A light shower after you spread fertilizer is usually good news, because it dissolves the granules and carries the nutrients down into the root zone. A heavy downpour right after application is bad news, because it can wash granules off the surface and push dissolved nutrients below the reach of the roots. Timing, intensity, soil type, and slope decide which outcome you get.",
      "Start with the good scenario. You spread granular fertilizer in the morning, and a gentle rain follows a few hours later. The granules dissolve, the nutrient solution moves a few centimetres into the soil, and the roots take it up over the coming days. In this case the rain did your incorporation work for you. Many farmers deliberately time their application just before a light, settled rain for exactly this reason.",
      "Now the bad scenario. You spread fertilizer on bare, sloping ground, and a thunderstorm hits within the hour. Water sheets across the surface, carrying undissolved granules with it into low spots, ditches, and waterways. What is not carried sideways can be pushed straight down: in sandy soils especially, dissolved nitrogen can leach below the root zone, where the crop can no longer reach it. The fertilizer is not just wasted; it ends up where you do not want it.",
      "Different nutrients behave differently in water, and this is worth understanding. Nitrogen in nitrate form is very mobile and moves easily with water, which is why it leaches first. Phosphorus mostly binds to soil particles near the surface and moves very little, so it is lost mainly through surface runoff carrying soil with it, not through leaching. Potassium sits somewhere in between. This is why nitrogen management is the most sensitive to rain timing.",
      "The timing of the rain relative to your application matters more than most people realise. Rain that arrives days after application, once granules have dissolved and nutrients have bound to the soil, causes far less loss than rain that arrives within minutes, while granules are still sitting exposed on the surface. The most dangerous window is the first few hours after spreading.",
      "Soil type changes the picture completely. Sandy soils drain fast, so they leach nutrients quickly but rarely suffer surface runoff. Clay soils drain slowly, so they resist leaching but are prone to runoff when heavy rain cannot soak in. Slope makes everything worse: on flat ground even moderate rain mostly soaks in, while on a slope it runs off. Bare soil loses far more than soil covered by a growing crop or mulch, because roots and cover slow the water down.",
      "There is a useful twist for urea users. Urea spread on the surface loses nitrogen to the air through volatilization, especially in warm weather. A light rain shortly after application actually reduces this loss by washing the urea into the soil, where it is protected. So with urea, a gentle rain is doubly helpful: it stops air losses and starts root feeding at the same time.",
      "Here is a practical routine for rainy seasons. Check the forecast before you spread and aim for a calm window of at least a day or two with no heavy rain expected. If light rain is forecast, that is fine, even ideal. Spread in the morning so granules have time to settle. On slopes, work the fertilizer lightly into the soil rather than leaving it on the surface. And keep a buffer strip near streams and ditches where you do not spread at all.",
      "If an unexpected storm hits right after you applied, do not panic and do not immediately reapply the full dose. Wait and observe. If you can still see undissolved granules washed into piles or rills, some loss has occurred, but the dissolved portion in the soil is still there. Reapplying blindly risks over-fertilizing, which can burn roots and waste money. When in doubt, apply a smaller corrective dose later rather than a full dose now.",
      "Split applications are the best insurance in rainy climates. Instead of putting all the nitrogen on at once, divide it into two or three smaller doses across the season. If one dose is hit by bad weather, the others still feed the crop. This practice, called split application, is standard advice in high-rainfall regions, and it also matches the crop's needs better, since plants take up most nitrogen during active growth, not all at once.",
      "The form of fertilizer matters too. Ordinary granular fertilizer dissolves quickly and is most exposed in the first hours. Slow-release and coated fertilizers release nutrients gradually, so a single storm washes away less. Liquid fertilizers sprayed on leaves are the most vulnerable of all to immediate rain, which is why foliar sprays should only go on when several dry hours are guaranteed.",
      "The most common mistakes are straightforward. Applying just before a forecast downpour is the biggest one. Spreading on waterlogged or frozen ground, where nothing can soak in, is another. Reapplying a full dose after rain without assessing what was lost leads to over-fertilization. And ignoring slope and soil type, treating a sandy hillside the same as flat clay, guarantees disappointment.",
      "There is also an environmental side to this. Fertilizer that runs off into ponds, streams, and rivers feeds algae instead of crops, and that is a genuine pollution problem in many farming regions. Keeping to the right dose, keeping buffer strips near water, and avoiding application before heavy rain are not just good economics; they keep nutrients on your field and out of the water.",
      "Rain is part of farming, not an enemy of it. The goal is to work with it: light rain as your incorporation partner, heavy rain as a signal to wait. Plan your applications around the forecast, split your nitrogen in wet seasons, and match the dose to the crop. The dose calculator at /calculator helps you get the amounts right, /fertilizers explains the products and their grades, and /faq answers common questions about timing and methods."
    ]
  },
  {
    "slug": "foliar-spray-vs-soil-application",
    "title": "Foliar Spray vs Soil Application: Which Is Better?",
    "excerpt": "Foliar spray vs soil application: soil feeding handles the bulk of a crop's NPK needs, while foliar sprays are best for quick correction of micronutrient deficiencies. Most crops need both, for different jobs.",
    "category": "Guides",
    "date": "2026-10-06",
    "readMinutes": 7,
    "image": "/blog/foliar-spray-vs-soil-application.webp",
    "body": [
      "Foliar spray vs soil application: which is better? Neither wins outright, because they do different jobs. Soil application is how you supply the bulk of a crop's nitrogen, phosphorus, and potassium, the macronutrients needed in large amounts. Foliar spraying, where dissolved nutrients are sprayed directly onto the leaves, is best for quick correction of specific deficiencies, especially micronutrients like zinc, iron, boron, and manganese. Most well-managed crops use soil feeding as the foundation and foliar sprays as the targeted tool.",
      "Soil application works through the roots, which are built for the job. Roots spread through a large volume of soil and absorb dissolved nutrients over weeks and months. When you place fertilizer in or on the soil, whether as a basal dose at planting or as top-dressing during growth, you are stocking the pantry the plant will draw from all season. There is simply no other practical way to deliver the tens or hundreds of kilograms per hectare that crops need.",
      "Foliar feeding works through the leaves, which can absorb small amounts of dissolved nutrients through their surface. The advantage is speed: a nutrient sprayed on the leaf reaches the plant's system within hours, while soil-applied nutrients can take days to become available, especially in cold or dry soil. The disadvantage is capacity: leaves can only take in tiny quantities, and anything beyond that burns them.",
      "This capacity limit is the key to the whole comparison. A wheat or rice crop might need over a hundred kilograms of nitrogen per hectare. You cannot deliver that through the leaves; the spray concentrations required would destroy the foliage many times over. But a zinc deficiency, which needs only a small amount of zinc to correct, is a perfect foliar job. Think of soil feeding as the main meals and foliar feeding as the vitamin tablet.",
      "Foliar sprays shine brightest in a few specific situations. One is a visible micronutrient deficiency, such as yellowing between leaf veins, where a quick spray can green the crop up within days. Another is when soil conditions lock nutrients up: in very alkaline soils, for example, iron and zinc become unavailable to roots, but leaves can still absorb them from a spray. A third is during critical growth stages, like flowering, when a small targeted boost can support the crop at exactly the right moment.",
      "Timing a foliar spray correctly is essential. Spray early in the morning or late in the evening, when temperatures are cool and the air is calm. The droplets need to stay wet on the leaf for a while so absorption can happen. Sprayed at midday, they dry in minutes, uptake stops, and the concentrated residue can scorch the leaf tissue. Never spray in strong wind either, because drift wastes product and can damage neighbouring crops.",
      "Concentration is where most foliar mistakes happen. Always mix at the rate on the product label, and when in doubt, go weaker rather than stronger. Urea can be used as a foliar spray at low concentrations for a quick nitrogen touch-up, but the margin between helpful and harmful is narrow, and soil application remains the main route for nitrogen. A good habit is to test any new spray mix on a small patch and check the leaves the next day before treating the whole field.",
      "Here is a sensible step-by-step for a foliar spray. First, confirm the deficiency or the need; do not spray on guesswork. Second, choose the right product and mix exactly to the label rate, using clean water. Third, check compatibility if you plan to mix with a pesticide, because some combinations react badly or lose effectiveness. Fourth, spray in the cool hours, covering the foliage evenly, including the undersides of leaves where absorption is often better. Fifth, watch the crop for a few days and note the response.",
      "Soil application has its own best practices. Apply the basal dose of phosphorus and potassium at or before planting, since phosphorus barely moves in the soil and needs to be near the young roots. Split the nitrogen into two or three top-dressings timed to the crop's active growth stages. Work granular fertilizer into the soil or water it in after spreading, especially urea, which loses nitrogen to the air when left on a hot surface.",
      "In practice, the two methods are usually combined rather than chosen between. A typical programme is soil-applied NPK for the foundation, decided with a proper dose calculation, plus one or two foliar sprays during the season for micronutrients or quick corrections. This is standard practice in many intensive vegetable and cereal systems: the soil does the heavy lifting, and the sprayer handles the fine-tuning.",
      "The common mistakes tell the story of what goes wrong. The biggest is trying to replace the basal soil dose with foliar sprays, which starves the crop while looking like action. Next is spraying at midday and burning the leaves. Then comes over-concentration, mixing incompatible products, and spraying dusty leaves, where a layer of dust blocks absorption. Each of these is avoidable with a little discipline.",
      "Cost and effort also differ. Soil application is simple: spread, incorporate, irrigate. Foliar spraying needs a sprayer, clean water, careful mixing, calm weather, and labour for every pass. That is fine for a high-value correction, but it makes no sense as the routine way to deliver bulk nutrients. Match the method to the job and the economics follow.",
      "So how do you decide quickly? If the need is large, routine, or seasonal, use the soil: basal doses, nitrogen top-dressing, phosphorus and potassium. If the need is small, urgent, or specific, use the leaf: a zinc or iron correction, a flowering-stage boost, a rescue treatment when roots cannot take up nutrients. When both apply, do both, each at the right time and rate.",
      "Start with the foundation: calculate the right soil dose for your crop and area with the tool at /calculator, learn what each fertilizer grade actually supplies at /fertilizers, and browse /faq for practical questions on mixing, timing, and application methods. Get the soil feeding right first, and foliar sprays become the precise finishing tool they are meant to be."
    ]
  },
  {
    "body": [
      "How long does urea last in soil? The short answer is that urea itself usually disappears within a few days, but the nitrogen it supplies typically remains available to crops for a few weeks — sometimes longer in cool conditions, sometimes much shorter in hot, dry, or sandy soils. Urea does not sit in the soil unchanged waiting for the plant. The moment it touches moist soil, a chain of transformations begins, and each step moves nitrogen into a form that is either easier for plants to use or easier to lose.",
      "Urea is the most concentrated solid nitrogen fertilizer in common use, carrying 46 percent nitrogen by weight. When a granule lands on moist soil, an enzyme called urease — which is naturally present in almost all soils — breaks the urea molecule down into ammonium. In warm, moist soil this first conversion is often complete within two to four days. That is why urea applied on the surface on a hot day can lose nitrogen to the air very quickly, while the same granule worked into the soil or washed in by irrigation stays put far longer.",
      "Once urea has become ammonium, the story enters its second phase. Soil bacteria — mainly from two groups that nitrify in sequence — convert ammonium first into nitrite and then into nitrate. This nitrification process typically takes one to four weeks depending on conditions, and it is the step that matters most for availability, because most crops take up nitrogen fastest in the nitrate form. Ammonium is held on soil particles and moves little; nitrate is mobile in soil water, which means it flows toward roots easily but can also be washed below the root zone by heavy rain.",
      "There is no single number for how long urea lasts because soil is a living system, not a warehouse. Warm soil speeds up every conversion step; cold soil slows them down, so nitrogen from a late-autumn application may persist in the ammonium form for many weeks while the same application in midsummer could be fully nitrified and leached within a fortnight. Moisture works the same way: microbial activity stalls in dry soil and races ahead in warm, damp soil. Soil texture and organic matter add their own influence, with heavier and richer soils holding ammonium longer than loose, sandy ones.",
      "The biggest way nitrogen leaves the system is through the air. When urea sits on the soil surface without being incorporated or watered in, some of the ammonium converts to ammonia gas and simply floats away — a process called volatilization. Losses are worst on alkaline soils, in hot and windy weather, and on fields with heavy crop residue on the surface. This is why agronomists consistently advise against broadcasting urea on the surface and leaving it there, especially in warm weather, and why a light irrigation or a timely rain right after application makes such a difference.",
      "The second major escape route is downward. Nitrate carries a negative charge, so soil particles cannot hold it, and it moves freely with water. In sandy soils, or under heavy rainfall or over-irrigation, nitrate can be washed below the root zone within days of forming. This is leaching, and it is one of the main reasons nitrogen recommendations split the total dose into two or three applications instead of putting everything down at sowing. Each split feeds the crop during the growth stage that needs it most and reduces the amount sitting exposed in the soil at any one time.",
      "A third pathway is denitrification, which happens in waterlogged, oxygen-poor soil. Under those conditions, other bacteria strip oxygen from nitrate and release nitrogen back into the air as harmless gas. Paddy fields, flooded patches, and poorly drained low spots lose nitrogen this way. It is a reminder that nitrogen management is not only about how much you apply but also about drainage and water management — nitrogen you cannot keep in the root zone is nitrogen you paid for and the crop never sees.",
      "In practical terms, what most farmers mean by how long urea lasts is how long the nitrogen keeps feeding the crop. Under typical warm-season conditions with the fertilizer incorporated or watered in, you can expect the nitrogen from one application to keep supplying the crop for roughly two to four weeks before most of it has been taken up, leached, or lost. That window is exactly why cereals like wheat and rice are usually fed nitrogen in splits — part at sowing or transplanting, and the rest as topdressing at tillering and flowering stages — rather than all at once.",
      "Application method matters more than most people realize. Working urea into the top few centimeters of soil, or following a broadcast application with irrigation, can cut volatilization losses dramatically compared with leaving granules on the surface. On standing crops where incorporation is impossible, applying urea just before an irrigation or a forecast rain achieves the same wash-in effect. Deep placement of urea, where equipment allows, puts the nitrogen below the surface layer where ammonia escape is strongest.",
      "There is also a class of products designed to slow the transformation chain: urease inhibitors delay the first conversion step, and nitrification inhibitors slow the ammonium-to-nitrate step, keeping nitrogen in the less mobile ammonium form for longer. These do not add nitrogen; they buy time. They can be worth considering in high-loss situations, such as surface applications in hot weather or on very sandy soils, but they do not replace good timing and incorporation.",
      "Cold weather deserves a special note. In late winter or early spring, soil microbes work slowly, so urea converts and nitrifies at a reduced pace. That sounds like a benefit — nitrogen lingers longer — but it also means the crop may face a temporary shortage when growth starts, because the soil is not yet releasing nitrogen fast enough to meet demand. Timing applications to match the crop's growth flush, rather than the calendar, usually gives better results than applying early and hoping the nitrogen waits around.",
      "How can you tell whether the nitrogen is still there? The most honest answer is that you cannot see nitrogen in soil, and guessing is expensive either way — too little costs yield, too much costs money and risks lodging and runoff. Soil testing before the season gives you a baseline, and tissue or leaf-color observations during the season tell you whether the crop is actually short. If your wheat or rice is pale despite an adequate basal dose, the missing nitrogen often went to the air or below the root zone, not into the plant.",
      "One final practical point: urea is an excellent fertilizer precisely because it converts quickly and completely, not because it lasts long. Its job is to become ammonium and then nitrate on schedule. Trying to make one application stretch across the whole season fights the chemistry of the soil. Working with the natural timeline — incorporating each application, splitting the total dose across growth stages, and keeping water management tight — turns urea's short residence time from a weakness into an advantage, because you are feeding the crop when it is hungriest.",
      "If you want to plan that timing precisely, start with the dose calculator at /calculator, which breaks your fertilizer into bags per acre or per hectare so you know exactly what each split costs. The crop pages under /crops show verified dose recommendations with their sources, /fertilizers explains what each product actually does in the soil, and the /faq answers common questions about mixing and applying. Getting the dose right matters, but as this article shows, getting the timing and placement right matters just as much."
    ],
    "category": "Fertilizers",
    "date": "2026-10-06",
    "excerpt": "Urea converts to plant-available nitrogen within days, but how long that nitrogen actually stays usable depends on temperature, moisture, soil pH, and how you apply it. Here is the timeline in plain words.",
    "image": "/blog/how-long-does-urea-last-in-soil.webp",
    "readMinutes": 9,
    "slug": "how-long-does-urea-last-in-soil",
    "title": "How Long Does Urea Last in Soil?"
  },
  {
    "body": [
      "Nitrogen deficiency symptoms in wheat almost always start the same way: the oldest, lowest leaves turn pale green, then yellow, beginning at the leaf tip and working inward, while the newest leaves at the top still look normal. This bottom-up pattern is the single most useful clue in the field. If the yellowing begins on the youngest leaves instead, you are likely looking at a different problem, such as sulfur deficiency, and treating for nitrogen will not fix it.",
      "The reason for this pattern lies in how the plant handles nitrogen. Nitrogen is mobile inside the plant, so when roots cannot supply enough, the wheat plant pulls nitrogen out of its older leaves and ships it to the growing tip, where new growth is happening. The older leaves are sacrificed first. That is why the crop can look acceptable from a distance — the top of the canopy stays green — while the lower canopy is clearly starving. Walking into the field and parting the canopy to look at the lower leaves is the correct way to check.",
      "As the deficiency deepens, the yellowing spreads upward leaf by leaf, and the whole plant takes on a pale, washed-out appearance. Growth slows visibly: plants stay short, stems grow thin, and tillering — the process where one wheat plant produces multiple productive shoots — drops off. Fewer tillers mean fewer ears per plant, and fewer ears per plant is one of the most direct routes to a lower harvest. Ears that do form are often smaller, and grain from nitrogen-starved wheat typically has lower protein content, which matters for both milling quality and market price.",
      "In severe cases the entire field develops a uniform yellow-green cast that is visible even from the road. Leaves may develop a slight pinkish or reddish tinge along the edges in some varieties, and the oldest leaves die back completely. By the time the flag leaf — the last leaf before the ear, which feeds most of the grain — starts yellowing early, a large part of the season's yield potential has already been lost, because the plant has been running short through the growth stages that set tiller number and grain number.",
      "The most common cause is simply under-dosing: the total nitrogen applied was below what the crop and the soil together could supply. But many fields are short of nitrogen despite an apparently adequate dose, and then the cause is loss rather than under-application. Heavy rain on light, sandy soils washes nitrate below the root zone. Waterlogged patches lose nitrogen to denitrification. Urea broadcast on the surface in warm weather loses ammonia to the air. And a delayed topdressing — the nitrogen arrives after the tillering window has closed — means the plant needed it when it was not there.",
      "A useful diagnostic habit is to compare patterns. Nitrogen deficiency moves from old leaves upward and is fairly uniform across the field, though low spots and sandy patches show it first. Sulfur deficiency also yellows leaves, but it starts on the youngest leaves because sulfur does not move inside the plant the way nitrogen does. Waterlogging makes the whole plant pale at once and usually comes with soggy soil and stunted roots. Herbicide injury or disease tends to show patches, streaks, or spots rather than the smooth bottom-up yellowing of nitrogen shortage. Getting the diagnosis right saves both money and time.",
      "Soil testing before the season is the best prevention, because it tells you the starting nitrogen status of your field instead of forcing you to guess. During the season, many extension services recommend leaf color charts — simple printed cards you hold against a leaf to judge greenness — as a low-cost way to decide whether a topdressing is actually needed. A wheat crop that is deep green at tillering probably does not need extra nitrogen yet; a crop fading to pale green at the same stage is asking for it. These observations beat the calendar as a timing guide.",
      "To correct a deficiency once you see it, the standard practice is a topdressing of urea, applied before an irrigation or a rain so the granules wash into the soil. The amount should follow your local recommendation or soil test result — a common working approach is to apply the planned topdress portion of the season's total nitrogen, typically split between tillering and jointing stages. Spreading urea on dry soil in hot weather without following water invites volatilization losses, so timing the topdress just ahead of irrigation is one of the highest-value details in wheat nitrogen management.",
      "Timing matters as much as amount. Nitrogen applied during tillering feeds tiller survival and ear number; nitrogen at jointing feeds grain number and grain protein. Nitrogen applied much later, after flowering, does little for yield and mostly risks lodging — the crop falls over — along with delayed maturity and wasted money. If you discover the deficiency late in the season, a modest correction can still help grain filling, but be realistic: nitrogen cannot rebuild tillers that were never formed.",
      "One mistake to avoid is overcorrecting. It is tempting to double the topdress when the crop looks hungry, but excess nitrogen makes wheat tall, soft-stemmed, and prone to lodging, delays ripening, and increases disease pressure in dense canopies. It also costs money twice — once for the fertilizer and once in the harvest you lose to a lodged crop. The goal of correction is to bring the crop back to an adequate, balanced level, not to push it beyond it. Follow the recommended dose, not the panic.",
      "Prevention for the next season starts with records. Note how much nitrogen you applied, when, how, and what the crop looked like at each stage. If the same field shows deficiency every year despite full doses, the problem is probably loss — leaching on sandy soil, poor drainage, or surface application — and the fix is a change in practice, not a bigger bag. Splitting the total nitrogen into two or three applications, incorporating the basal dose at sowing, and keeping drainage open are the three most reliable preventive habits.",
      "Balanced nutrition also helps nitrogen do its job. Phosphorus and potassium deficiencies limit root growth and overall vigor, which makes nitrogen uptake less efficient even when nitrogen is present. A crop short of everything often looks short of nitrogen first, because nitrogen symptoms appear earliest. That is another reason a pre-season soil test is worth its cost: it tells you which nutrient is actually limiting, so you correct the right one.",
      "Finally, remember that wheat varieties, soils, and climates differ, and no article can replace a local recommendation. The symptom descriptions here help you read your field, but the exact dose and timing for your area should come from your agricultural extension service, a soil test report, or the verified recommendations published for your region. Diagnosis is in your hands; the prescription should be grounded in local data.",
      "To put a precise number on your correction, use the dose calculator at /calculator — enter your crop and area and it works out the urea and DAP quantities per acre or per hectare. The verified crop recommendations under /crops give region-specific doses with their sources, /fertilizers explains how urea behaves in soil, and the /faq covers practical questions about splitting and mixing fertilizers. Catching nitrogen deficiency early and correcting it with the right amount at the right time is one of the cheapest yield gains available in wheat farming."
    ],
    "category": "Crop Nutrition",
    "date": "2026-10-06",
    "excerpt": "Yellowing that starts on the oldest, lowest leaves and moves upward is the classic sign of nitrogen shortage in wheat. Learn to read the symptoms, find the cause, and correct it without overdoing the topdress.",
    "image": "/blog/nitrogen-deficiency-symptoms-wheat.webp",
    "readMinutes": 9,
    "slug": "nitrogen-deficiency-symptoms-wheat",
    "title": "Nitrogen Deficiency in Wheat: Symptoms and How to Correct It"
  },
  {
    "body": [
      "Phosphorus deficiency in rice shows up as a distinctive combination: plants stay short and stunted, leaves take on an unusually dark, bluish-green color, and a reddish-purple discoloration spreads across the leaf blades and sheaths. Tillering drops off sharply, and the whole crop looks like it stopped growing weeks ago while the calendar kept moving. If your rice is short, dark, and purpling instead of tall and green, phosphorus is the first suspect.",
      "The purple color is the plant's stress response, not a disease. When phosphorus is scarce, the plant cannot move sugars out of the leaves efficiently, and it responds by producing reddish-purple pigments called anthocyanins in the leaf tissue. This purpling typically appears first on the older, lower leaves and on the leaf sheaths near the base of the plant, and in young seedlings it can be strikingly visible. A healthy rice leaf is a bright, fresh green; a phosphorus-starved one is dark, dull, and tinged with purple.",
      "Unlike the yellowing of nitrogen deficiency, phosphorus-deficient rice rarely looks pale. The dark green color can actually mislead farmers into thinking the crop has plenty of nutrition, when the opposite is true — the darkness comes from stunted cells packed with chlorophyll, not from vigorous growth. The real giveaway is the growth itself: short plants, thin stems, few tillers, and slow development. Roots are often poorly developed too, which you can confirm by pulling up a plant and comparing its root mass with a healthy one from a good patch of the same field.",
      "Because phosphorus is mobile inside the plant, deficiency symptoms generally appear on older leaves first as the plant moves its limited supply to new growth — though in rice the purpling is often most obvious on young, actively stressed plants. Delayed maturity is another classic sign: phosphorus-starved rice heads late and ripens unevenly, because the energy-transfer processes that phosphorus drives are running at half speed through the entire season.",
      "The underlying cause is usually not that the soil contains no phosphorus, but that the plant cannot reach it. In acidic soils, phosphorus gets locked up with iron and aluminum into forms roots cannot absorb; in strongly alkaline soils, it binds with calcium with the same result. Cold weather early in the season slows root activity and phosphorus uptake, which is why deficiency symptoms often appear in young transplanted rice and then ease as the weather warms. Low organic matter, eroded topsoil, and fertilizer placed far from the root zone all make the problem worse.",
      "This lock-up behavior explains the single most important fact about phosphorus management: phosphorus barely moves in soil. A granule of DAP or single super phosphate dissolves, and the phosphorus is quickly held by soil particles within a centimeter or two of where it landed. Broadcasting phosphorus on the surface of a flooded paddy, far from the roots, is far less effective than placing it in or near the root zone at transplanting. With phosphorus, placement is the dose.",
      "Correcting a deficiency starts with getting phosphate fertilizer into the root zone as early as possible. The standard practice across rice-growing regions is to apply the full phosphorus dose as a basal application — at or before transplanting, incorporated into the soil where young roots will find it — using DAP or single super phosphate according to local recommendations. Because phosphorus does not move to the roots on its own, topdressing phosphorus later in the season is inefficient; the correction has to happen at the start, which makes early diagnosis valuable.",
      "If you only notice the symptoms mid-season, be honest about what correction can achieve. Adding phosphorus late will not undo stunting that has already happened, because the tillering window is closed. A late application can still help grain development to some degree, but the return is much smaller than the same fertilizer applied at transplanting. This is why prevention — soil testing and a proper basal dose — is worth far more than rescue with phosphorus.",
      "Foliar feeding deserves a clear word of caution. Spraying a dilute phosphate solution on the leaves can green up the crop temporarily and is sometimes used as an emergency measure, but leaves can only absorb tiny amounts compared with what the roots need for the whole season. Foliar sprays cannot substitute for soil-applied phosphorus in rice; at best they buy a little time while you fix the real problem, which is supply in the root zone.",
      "Resist the urge to over-apply as insurance. Excess phosphorus does not make rice grow faster once the requirement is met, and it costs money for no return. Very high phosphorus applications can also interfere with the uptake of zinc and iron, which are already tricky nutrients in flooded rice soils — trading one deficiency for another is a poor bargain. A soil test tells you whether your field is low, medium, or high in available phosphorus, and the dose should match that result, not your anxiety.",
      "Prevention is straightforward and mostly happens before transplanting. Test the soil so you know the starting phosphorus level. In acidic soils, liming according to the test report improves phosphorus availability by reducing iron and aluminum lock-up. Maintaining organic matter through crop residue or farmyard manure helps keep phosphorus in plant-available forms. And placing the basal phosphate dose in the root zone at transplanting — rather than broadcasting it on the surface or skipping it because nitrogen gets all the attention — closes the loop.",
      "Water management plays a supporting role. In flooded paddies, phosphorus availability generally improves after submergence as the soil chemistry shifts, but prolonged deep flooding or poor drainage brings its own problems. Keeping the field level so that water depth is uniform helps the basal phosphorus work evenly across the plot instead of feeding only the low spots. Small details of field leveling and water control often matter more for phosphorus efficiency than the brand of fertilizer.",
      "Keep notes on what you observe. Phosphorus deficiency tends to recur in the same fields and the same patches year after year, because the underlying cause — acidic soil, eroded topsoil, or a history of skipped basal doses — does not fix itself. A field that purples every season at the seedling stage is telling you something specific, and a soil test will usually confirm it. Treat the cause once, properly, and the symptom stops appearing.",
      "To plan the correction with real numbers, open the dose calculator at /calculator and work out your phosphate requirement per acre or per hectare from the crop and area you enter. The verified recommendations under /crops list region-specific NPK doses with their sources, /fertilizers explains how DAP and other phosphate products behave in soil, and the /planting-calendar helps you time transplanting and basal application together. With phosphorus, the lesson of this article is simple: put the right amount in the root zone at the start, and the crop will do the rest."
    ],
    "category": "Crop Nutrition",
    "date": "2026-10-06",
    "excerpt": "Stunted plants with dark, bluish-green leaves and purple discoloration are the hallmark of phosphorus shortage in rice. Because phosphorus barely moves in soil, placement and timing matter more than the product you choose.",
    "image": "/blog/phosphorus-deficiency-symptoms-rice.webp",
    "readMinutes": 9,
    "slug": "phosphorus-deficiency-symptoms-rice",
    "title": "Phosphorus Deficiency in Rice: Symptoms and How to Correct It"
  }
];

export function getPost(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}
